version: "3"
services:
  jti-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "jti-bot"
    restart: always
    env_file:
      - .env

networks:
  default:
    name: jti-network
